force-app/main/default/objects/Account/fields/allow_deposits__c.field-meta.xml
<CustomField>
    <fullName>allow_deposits__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Deposits</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/allow_payments__c.field-meta.xml
<CustomField>
    <fullName>allow_payments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Payments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/company_code__c.field-meta.xml
<CustomField>
    <fullName>company_code__c</fullName>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/distribution_channel__c.field-meta.xml
<CustomField>
    <fullName>distribution_channel__c</fullName>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/division__c.field-meta.xml
<CustomField>
    <fullName>division__c</fullName>
    <label>Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/sales_organization__c.field-meta.xml
<CustomField>
    <fullName>sales_organization__c</fullName>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountAPI.cls
@RestResource(urlMapping='/accounts/*')
global with sharing class AccountAPI {

    @HttpGet
    global static void getAccountsByUser() {

        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        try {
            String userId = req.params.get('userId');

            if (String.isBlank(userId)) {
                res.statusCode = 400;
                res.responseBody = Blob.valueOf(
                    JSON.serialize(new ErrorResponse('userId is required'))
                );
                return;
            }

            List<Account> accounts = [
                SELECT Id,
                       Name,
                       OwnerId,Type,Sales_Organization__c,distribution_channel__c,division__c,
                        company_code__c,allow_payments__c,allow_deposits__c
                FROM Account
                WHERE OwnerId = :userId
                ORDER BY Name
            ];

            List<AccountResponse> response = new List<AccountResponse>();

            for(Account acc : accounts){
                AccountResponse ar = new AccountResponse();
                ar.accountId = acc.Id;
                ar.accountName = acc.Name;
                ar.userId = acc.OwnerId;
                ar.phone = acc.Phone;
                ar.billingStreet = acc.BillingStreet;
                ar.billingCity = acc.BillingCity;
                ar.billingState = acc.BillingState;
                ar.billingCountry = acc.BillingCountry;
                response.add(ar);
            }

            res.statusCode = 200;
            res.addHeader('Content-Type','application/json');
            res.responseBody = Blob.valueOf(JSON.serialize(response));

        } catch(Exception e){
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(
                JSON.serialize(new ErrorResponse(e.getMessage()))
            );
        }
    }

    global class AccountResponse {
        public String accountId;
        public String accountName;
        public String userId;
        public String phone;
        public String billingStreet;
        public String billingCity;
        public String billingState;
        public String billingCountry;
    }

    global class ErrorResponse {
        public String message;

        public ErrorResponse(String msg){
            message = msg;
        }
    }
}